# Generated by Django 4.1.2 on 2022-10-25 09:23

import django.core.validators
from django.db import migrations, models
import expenses_tracker_stan.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), expenses_tracker_stan.web.validators.validate_name_consist_letters_only])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), expenses_tracker_stan.web.validators.validate_name_consist_letters_only])),
                ('budget', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image', validators=[expenses_tracker_stan.web.validators.ImageMaxSizeLimit(5)])),
            ],
        ),
    ]
